### ISSUE TITLE
Unchecking a hidden category does not always show it

### ISSUE THREAD

**Issue by jonathathan** [schrauger/mint.com-customize-default-categories#3]
Hey, really enjoying the script so far, less a couple of bugs! 

Marking a category as hidden does not always hide it, and unmarking it as unhidden does not always show it. [Here is a video](https://www.dropbox.com/s/6bvumf9x5o377nx/splitwise-bug.mov?dl=0) demonstrating that the "Auto & Transport" category, when unchecked, does not get shown or stay unchecked.

Happy to provide any info I can to help debug!

**Comment by schrauger** [comment]
Interesting. I'll look into that. I don't have a Mac, but I can try it on Chrome on a couple machines. Thanks for the video; it's really helpful to be able to see exactly what happens!

**Comment by sergiover** [comment]
I'm experiencing the exact same issue displayed in the video jonathathan share. I'm using Windows 10 and running the script in Chrome 49.0.2623.110 m. Any suggestions? Should I use Firefox instead?

**Comment by schrauger** [comment]
Sorry guys, I've been busy and haven't been able to work on this yet. But I haven't forgotten it, and I was able to reproduce it as well. I'll work on it soon. :-)

**Comment by sergiover** [comment]
No worries!! On the contrary, thanks so much for the contribution!!

**Comment by JasmineBowen** [comment]
Hi all,

Love this script, but I am experiencing the same problem - I'm trying to "uncheck" a few hidden categories, but the changes do not seem to stick once saved.  I am using Firefox 46.0.1 on a Mac 10.8.5.  Are there any debugging updates out there?  I am also willing to provide details to help with the debugging process.

Thank you so much!

**Comment by schrauger** [comment]
I think I've fixed this bug now. At least, I can no longer reproduce it on Chrome or Firefox on both Linux and Windows 7.

@sergiover Can you confirm the bug is fixed for you?

@JasmineBowen and @jonathathan Can you check your browsers on your Macs to see if it's fixed?

The script should have auto-updated, but if not, make sure to load the latest version (1.3.4).

**Comment by JasmineBowen** [comment]
@schrauger thank you so much for working on this.  I really appreciate the prompt attention to and maintenance of your script.  

I downloaded 1.3.4 and restarted firefox, but unfortunately I am still experiencing the same issue.  I am curious to see if this is also the case for others? @sergiover @jonathathan

**Comment by sergiover** [comment]
@schrauger and @JasmineBowen: Sorry I'm this late in getting back to you both. I just manually updated the script to 1.3.4, restarted Chrome (version 51.0.2704.106 m running on Windows 10) and I'm still experiencing the same issue. 

@schrauger Please let me know if you need more details in order to get it fixed. Thank you very much for your hard work :-)

**Comment by rkhachey** [comment]
Hi! I've also been having this problem - specifically with the Income/Paycheck and Uncategorized categories. Although I unchecked the box, these categories will not show. I'm using Chrome (Version 51.0.2704.103 m) on Windows 7. Thanks in advance!

**Comment by schrauger** [comment]
@rkhachey @sergiover @JasmineBowen @jonathathan Can you please copy and paste the 3 preference strings from your mint categories? These are the 3 fields used by this script to store the show/hide preferences.

The fields are hidden by the script, so you'll need to disable the script first. Then, go to mint's category editor (Manage Your Categories) and click on the Uncategorized top level category. Inside there will be 3 custom categories, beginning with `#!1`, `#!2`, and `#!3`.

Please copy those three fields and paste them here. I'll be able to see if there's some problem with my preference saving or restoring that's causing your categories to remain hidden even after you uncheck them and save.

Thanks!

**Comment by sergiover** [comment]
Hi Stephen,

Thank you so much for following up on this. I did as you instructed and in my case I not only have 3 custom categories, but actually 8! Here they are:

```
#!1 _@@@@@@@@@hC@@@@
#!1 _@kal@WCf|hC@@@@
#!1 _@kal@WCf|hC@@G`
#!2 G@B`l@G@f@H@@@@@
#!2 G@R`@@C@H@@@{AE@
#!2 G@R`JBC@H@O@{AE@
#!3 _@C`@@UAF`H@@@@@
#!3 _@C`C@}AF`_`@`@@
```

Please let me know if there is any further information you may need. Thanks again!

Update: I just noted that after saving this comment the HTML messes up some of the strings. Here is a screenshot so you can double check: http://take.ms/j7rn6

Edit by @schrauger: I put the strings within a code block to prevent Markdown from interpreting the strings.

**Comment by schrauger** [comment]
@sergiover That definitely points to a problem with my script. It looks like it's saving your new preferences, but not overwriting the old ones, causing problems.

This really helps, and I should be able to do more testing soon. Thanks!

**Comment by schrauger** [comment]
Sorry for the long delay. This has finally been fixed. You may need to Edit your hidden categories, Save them, then refresh the page. That will get rid of the duplicate preference fields. Then, modify your hidden categories again to make sure the categories are set the way you want them.

Hopefully, the changes to the script will prevent this in the future as well.

**Comment by sergiover** [comment]
@schrauger: thanks so much for working on this. I just tested in Chrome and seems to work properly. I'll keep an eye on it!

Many thanks again and happy holidays!

**Comment by schrauger** [comment]
Thanks, @sergiover! Merry Christmas!

**Comment by schrauger** [comment]
I'm closing this bug, since my update should take care of this issue caused by duplicated preference strings. Feel free to comment or open a new issue if you're still having problems.
